# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a17a6c10727734f778e809e9362ee1b014b461b273370029e7dc9f9d74a1f9b0efa7eb1e2f7134f1f0f5e34deecbaf72fe4f1eb47a8eae153b48d3209aad5fb

test:
  secret_key_base: 73a1e7584be5339a967b165887514def135f75de94307ef548982dd3ad87ea6f5f53b4f6aa91b64074f5cc50fd6bbc3ed42d81af3b55a6135cdd2b29c8aec749

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
